name: CI Azure Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Node.js
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.x"  # Using Node 18.x since this is what Azure App Service is configured for

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Optional: Run tests (uncomment if you want to add tests)
      #- name: Run tests
      #  run: npm test

      # Build your project (if necessary)
      - name: Build the app
        run: npm run build # Adjust if needed

  # Deploy to Azure App Service
  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      # Checks out your repository again for the deploy step
      - uses: actions/checkout@v2

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'your-app-service-name'  # The name of your Azure App Service
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Azure Publish Profile secret
          package: .

